<?xml version="1.0" encoding="ISO-8859-1"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output encoding="ISO-8859-1" media-type="text/plain" indent="yes"/>
	<xsl:include href="./EJBUtils.xsl"/>
	<xsl:template match="/child::*[local-name()='definitions']">	
package com.twinsoft.convertigo.ejb;

/**
 * Session layer for <xsl:call-template name="getClassNameOfCurrent"/>EJB.
 * Automatically generated by twinsoft Convertigo.
 */
public class <xsl:call-template name="getClassNameOfCurrent"/>EJBSession extends com.twinsoft.convertigo.ejb.<xsl:call-template name="getClassNameOfCurrent"/>EJBBean implements javax.ejb.SessionBean {
	public void ejbActivate() {}
	public void ejbPassivate() {}
	public void setSessionContext(javax.ejb.SessionContext ctx) {}
	public void unsetSessionContext() {}
	public void ejbRemove() {}
}
	</xsl:template>
</xsl:stylesheet>