<?xml version="1.0" encoding="ISO-8859-1"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output encoding="ISO-8859-1" media-type="text/xml" indent="yes"/>
	<xsl:include href="./EJBUtils.xsl"/>
	
	<xsl:template match="/child::*[local-name()='definitions']">	
	
<xsl:text disable-output-escaping="yes">&lt;!DOCTYPE jrun-ejb-jar PUBLIC "-//Macromedia, Inc.//DTD jrun-ejb-jar 4.0//EN" "http://jrun.macromedia.com/dtds/jrun-ejb-jar.dtd"&gt;</xsl:text>

<jrun-ejb-jar>
 <description><![CDATA[Generated by Convertigo]]></description>
  <source>DefaultDataSource</source>
  <enterprise-beans>
    <session>
      <ejb-name><xsl:call-template name="getClassNameOfCurrent"/>EJB</ejb-name>
      <jndi-name><xsl:call-template name="getClassNameOfCurrent"/>Bean</jndi-name>
    </session>
  </enterprise-beans>
  <ejb-container>
  <!--
    Define ejb-container in a file called ejb-container.xml and place
    it in your merge directory.
  -->
  </ejb-container>
</jrun-ejb-jar>
	</xsl:template>
</xsl:stylesheet>