/*
 * This file is generated by npm run update:bezels.
 * Update config/device-catalog.json then rerun the script.
 */
const devices = {
	'iPhone-16': {
		title: 'iPhone 16',
		type: 'phone',
		iframe: {
			width: 393,
			height: 852,
			marginTop: 52,
			marginLeft: 55,
			borderRadius: 35
		},
		bezel: {
			width: 503,
			height: 955
		},
		id: 'iPhone-16',
		index: 0
	},
	'iPhone-16-Plus': {
		title: 'iPhone 16 Plus',
		type: 'phone',
		iframe: {
			width: 430,
			height: 932,
			marginTop: 33,
			marginLeft: 33,
			borderRadius: 35
		},
		bezel: {
			width: 497,
			height: 999
		},
		id: 'iPhone-16-Plus',
		index: 1
	},
	'iPhone-16-Pro': {
		title: 'iPhone 16 Pro',
		type: 'phone',
		iframe: {
			width: 402,
			height: 874,
			marginTop: 33,
			marginLeft: 34,
			borderRadius: 19
		},
		bezel: {
			width: 469,
			height: 941
		},
		id: 'iPhone-16-Pro',
		index: 2
	},
	'iPhone-16-Pro-Max': {
		title: 'iPhone 16 Pro Max',
		type: 'phone',
		iframe: {
			width: 440,
			height: 956,
			marginTop: 52,
			marginLeft: 56,
			borderRadius: 19
		},
		bezel: {
			width: 550,
			height: 1059
		},
		id: 'iPhone-16-Pro-Max',
		index: 3
	},
	'Google-Pixel-9-Pro': {
		title: 'Google Pixel 9 Pro',
		type: 'phone',
		iframe: {
			width: 411,
			height: 917,
			marginTop: 46,
			marginLeft: 55,
			borderRadius: 31
		},
		bezel: {
			width: 520,
			height: 1007
		},
		id: 'Google-Pixel-9-Pro',
		index: 4
	},
	'Google-Pixel-9-Pro-XL': {
		title: 'Google Pixel 9 Pro XL',
		type: 'phone',
		iframe: {
			width: 430,
			height: 957,
			marginTop: 45,
			marginLeft: 54,
			borderRadius: 33
		},
		bezel: {
			width: 539,
			height: 1047
		},
		id: 'Google-Pixel-9-Pro-XL',
		index: 5
	},
	'Google-Pixel-8-Pro': {
		title: 'Google Pixel 8 Pro',
		type: 'phone',
		iframe: {
			width: 412,
			height: 917,
			marginTop: 18,
			marginLeft: 17,
			borderRadius: 30
		},
		bezel: {
			width: 452,
			height: 954
		},
		id: 'Google-Pixel-8-Pro',
		index: 6
	},
	'Galaxy-S24': {
		title: 'Galaxy S24',
		type: 'phone',
		iframe: {
			width: 360,
			height: 779,
			marginTop: 12,
			marginLeft: 14,
			borderRadius: 24
		},
		bezel: {
			width: 391,
			height: 805
		},
		id: 'Galaxy-S24',
		index: 7
	},
	'Galaxy-S24-Plus': {
		title: 'Galaxy S24 Plus',
		type: 'phone',
		iframe: {
			width: 384,
			height: 832,
			marginTop: 14,
			marginLeft: 15,
			borderRadius: 23
		},
		bezel: {
			width: 416,
			height: 861
		},
		id: 'Galaxy-S24-Plus',
		index: 8
	},
	'Galaxy-S24-Ultra': {
		title: 'Galaxy S24 Ultra',
		type: 'phone',
		iframe: {
			width: 384,
			height: 833,
			marginTop: 10,
			marginLeft: 10,
			borderRadius: 2
		},
		bezel: {
			width: 408,
			height: 857
		},
		id: 'Galaxy-S24-Ultra',
		index: 9
	},
	'iPad-Air-11-M2': {
		title: 'iPad Air 11" (M2)',
		type: 'tablet',
		iframe: {
			width: 820,
			height: 1180,
			marginTop: 107,
			marginLeft: 107,
			borderRadius: 20
		},
		bezel: {
			width: 1034,
			height: 1394
		},
		id: 'iPad-Air-11-M2',
		index: 10
	},
	'iPad-Pro-11-M4': {
		title: 'iPad Pro 11" (M4)',
		type: 'tablet',
		iframe: {
			width: 834,
			height: 1210,
			marginTop: 92,
			marginLeft: 100,
			borderRadius: 31
		},
		bezel: {
			width: 1034,
			height: 1394
		},
		id: 'iPad-Pro-11-M4',
		index: 11
	},
	'iPad-Pro-13-M4': {
		title: 'iPad Pro 13" (M4)',
		type: 'tablet',
		iframe: {
			width: 1024,
			height: 1365,
			marginTop: 94,
			marginLeft: 95,
			borderRadius: 29
		},
		bezel: {
			width: 1215,
			height: 1554
		},
		id: 'iPad-Pro-13-M4',
		index: 12
	},
	'iPhone-15': {
		title: 'iPhone 15',
		type: 'phone',
		iframe: {
			width: 393,
			height: 849,
			marginTop: 20,
			marginLeft: 24,
			borderRadius: 30
		},
		bezel: {
			width: 443,
			height: 895
		},
		id: 'iPhone-15',
		index: 13
	},
	'iPhone-15-Plus': {
		title: 'iPhone 15 Plus',
		type: 'phone',
		iframe: {
			width: 430,
			height: 931,
			marginTop: 22,
			marginLeft: 25,
			borderRadius: 46
		},
		bezel: {
			width: 487,
			height: 985
		},
		id: 'iPhone-15-Plus',
		index: 14
	},
	'MacBook-Pro-16': {
		title: 'MacBook Pro 16"',
		type: 'desktop',
		iframe: {
			width: 1728,
			height: 1117,
			marginTop: 157,
			marginLeft: 222,
			borderRadius: 23
		},
		bezel: {
			width: 2171,
			height: 1431
		},
		id: 'MacBook-Pro-16',
		index: 15
	},
	'MacBook-Air-13': {
		title: 'MacBook Air 13"',
		type: 'desktop',
		iframe: {
			width: 1470,
			height: 956,
			marginTop: 125,
			marginLeft: 189,
			borderRadius: 30
		},
		bezel: {
			width: 1849,
			height: 1206
		},
		id: 'MacBook-Air-13',
		index: 16
	},
	'Dell-XPS-13': {
		title: 'Dell XPS 13',
		type: 'desktop',
		iframe: {
			width: 1920,
			height: 1199,
			marginTop: 142,
			marginLeft: 284,
			borderRadius: 0
		},
		bezel: {
			width: 2489,
			height: 1483
		},
		id: 'Dell-XPS-13',
		index: 17
	},
	'iMac-24': {
		title: 'iMac 24"',
		type: 'desktop',
		iframe: {
			width: 4480,
			height: 2520,
			marginTop: 200,
			marginLeft: 200,
			borderRadius: 0
		},
		bezel: {
			width: 4880,
			height: 4140
		},
		id: 'iMac-24',
		index: 18
	},
	'Dell-UltraSharp-5K': {
		title: 'Dell UltraSharp 5K 27"',
		type: 'desktop',
		iframe: {
			width: 5120,
			height: 2880,
			marginTop: 200,
			marginLeft: 200,
			borderRadius: 0
		},
		bezel: {
			width: 5520,
			height: 4436
		},
		id: 'Dell-UltraSharp-5K',
		index: 19
	},
	none: {
		title: 'None',
		iframe: { width: '100%', height: '100%', position: 'relative' },
		bezel: { width: '100%', height: '100%', position: 'relative' },
		type: 'desktop',
		id: 'none',
		index: 20
	}
};

export default devices;
