DROP TABLE IF EXISTS CacheTable;
CREATE TABLE CacheTable ( Id INT NOT NULL AUTO_INCREMENT PRIMARY KEY, RequestString VARCHAR(255), ExpiryDate BIGINT(15) NOT NULL, SheetUrl VARCHAR(255), AbsoluteSheetUrl VARCHAR(255), ContentType VARCHAR(255), Xml TEXT NOT NULL, Project VARCHAR(20),Transaction VARCHAR(30) );
