<?xml version="1.0" encoding="ISO-8859-1"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform">
	<xsl:output encoding="ISO-8859-1" media-type="text/plain" indent="yes"/>
	<xsl:include href="./EJBUtils.xsl"/>
	<xsl:template match="/child::*[local-name()='definitions']">
package com.twinsoft.convertigo.ejb;

import java.lang.String;
import localhost.convertigo.projects.<xsl:value-of select="@name"/>.<xsl:value-of select="@name"/>_ws.*;

/**
 * Remote interface for <xsl:call-template name="getClassNameOfCurrent"/>EJB.
 * Automatically generated by twinsoft Convertigo.
 */
public interface <xsl:call-template name="getClassNameOfCurrent"/>EJB extends javax.ejb.EJBObject{

	public java.net.URL getConvertigoServerAddress() throws java.rmi.RemoteException;
	
	public void setConvertigoServerAddress(java.net.URL convertigoServerAddress) throws java.rmi.RemoteException;
<xsl:for-each select="child::*[local-name()='portType']/child::*[local-name()='operation']">

	public <xsl:call-template name="getResponseClass"/> t<xsl:value-of select="@name"/>(<xsl:call-template name="getTypeAndParameters"/>) throws java.rmi.RemoteException;
</xsl:for-each>
}
	</xsl:template>
</xsl:stylesheet>
