<?xml version="1.0" encoding="ISO-8859-1"?>
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format" version="1.0" xmlns:fox="http://xml.apache.org/fop/extensions">
	<xsl:param name="strProject">Project</xsl:param>
	<xsl:param name="strProperties">Properties</xsl:param>
	<xsl:param name="strTransactions">Transactions</xsl:param>
	<xsl:param name="strScreen_classes">Screen classes</xsl:param>
	<xsl:param name="strProject_report">Project report</xsl:param>
	<xsl:param name="strGenerated_by">generated by</xsl:param>
	<xsl:param name="stron">on</xsl:param>
	<xsl:param name="strEngine_version">Engine version:</xsl:param>
	<xsl:param name="strObjects_version">Objects version:</xsl:param>
	<xsl:param name="strStudio_version">Studio version:</xsl:param>
	<xsl:param name="strPage">Page</xsl:param>
	<xsl:param name="strProject_index">Project index</xsl:param>
	<xsl:param name="strThis_document_concerns_the_technical_report_of_project">This document concerns the technical report of project</xsl:param>
	<xsl:param name="strComments">Comments:</xsl:param>
	<xsl:param name="strnone">none</xsl:param>
	<xsl:param name="strNone">None</xsl:param>
	<xsl:param name="strNone_1">None</xsl:param>
	<xsl:param name="strProject_definition">Project definition</xsl:param>
	<xsl:param name="strScreen_classes_handlers">Screen classes handlers</xsl:param>
	<xsl:param name="strStyle_sheets">Style sheets</xsl:param>
	<xsl:param name="strCriteria">Criteria</xsl:param>
	<xsl:param name="strExtraction_rules">Extraction rules</xsl:param>
	<xsl:param name="strInherited_screen_classes">Inherited screen classes</xsl:param>

	<xsl:param name="strName">Name</xsl:param>
	<xsl:param name="strValue">Value</xsl:param>

	<xsl:param name="strClass_name_used_for_this_object">Class name used for this object</xsl:param>
	<xsl:param name="strClass_version_used_for_this_object">Class version used for this object</xsl:param>
	<xsl:param name="strObject_priority">Object priority</xsl:param>
	<xsl:param name="strEmulator_used">Emulator used</xsl:param>
	
	<xsl:param name="strEmulatorID_1">Videotex (Minitel)</xsl:param>
	<xsl:param name="strEmulatorID_2">Unix (VT220)</xsl:param>
	<xsl:param name="strEmulatorID_3">Bull DKU 7107</xsl:param>
	<xsl:param name="strEmulatorID_4">Unknown code</xsl:param>
	<xsl:param name="strEmulatorID_5">IBM 3270</xsl:param>
	<xsl:param name="strEmulatorID_6">Unknown code</xsl:param>
	<xsl:param name="strEmulatorID_7">IBM 5250 (AS/400)</xsl:param>

	<xsl:param name="strDefault_transaction">Default transaction</xsl:param>

	<xsl:param name="strSelectionScreenZone_left">left:</xsl:param>
	<xsl:param name="strSelectionScreenZone_top">; top:</xsl:param>
	<xsl:param name="strSelectionScreenZone_width">; width:</xsl:param>
	<xsl:param name="strSelectionScreenZone_height">; height:</xsl:param>

	<xsl:param name="strKeyword_Table">Keyword, Data to send, Remplacement text, Action</xsl:param>
	<xsl:param name="strBrowserDefinitions">Label, Keyword</xsl:param>
	<xsl:param name="strTable">Value, Command to send, Label</xsl:param>
	<xsl:param name="strColumns">Label, First column, Last column</xsl:param>
	<xsl:param name="strChoice">Label, Command</xsl:param>

	<xsl:param name="strNo_attribute">No attribute</xsl:param>
	<xsl:param name="strSheetLocation_0">None</xsl:param>
	<xsl:param name="strSheetLocation_1">Transaction</xsl:param>
	<xsl:param name="strSheetLocation_2">Last detected screen class</xsl:param>

	<xsl:param name="strUnknowed_value">Unknowed value</xsl:param>

	<xsl:param name="strIncludedTagAttributes_1">Name:</xsl:param>
	<xsl:param name="strIncludedTagAttributes_2">Type:</xsl:param>
	<xsl:param name="strIncludedTagAttributes_3">Column:</xsl:param>
	<xsl:param name="strIncludedTagAttributes_4">Line:</xsl:param>
	<xsl:param name="strIncludedTagAttributes_5">Foreground:</xsl:param>
	<xsl:param name="strIncludedTagAttributes_6">Background:</xsl:param>
	<xsl:param name="strIncludedTagAttributes_7">Reverse:</xsl:param>
	<xsl:param name="strIncludedTagAttributes_8">Blink:</xsl:param>
	<xsl:param name="strIncludedTagAttributes_9">Underline:</xsl:param>
	<xsl:param name="strIncludedTagAttributes_10">Intense:</xsl:param>
	<xsl:param name="strIncludedTagAttributes_11">Optional: </xsl:param>

	<xsl:param name="strBlink">Blink</xsl:param>
	<xsl:param name="strBold">Bold</xsl:param>
	<xsl:param name="strInvert">Invert</xsl:param>
	<xsl:param name="strUnderline">Underline</xsl:param>

	<xsl:param name="strBlack_font">Black font</xsl:param>
	<xsl:param name="strRed_font">Red font</xsl:param>
	<xsl:param name="strGreen_font">Green font</xsl:param>
	<xsl:param name="strYellow_font">Yellow font</xsl:param>
	<xsl:param name="strBlue_font">Blue font</xsl:param>
	<xsl:param name="strMagenta_font">Magenta font</xsl:param>
	<xsl:param name="strCyan_font">Cyan font</xsl:param>
	<xsl:param name="strWhite_font">White font</xsl:param>
	<xsl:param name="strUnknown_font_color">Unknown font color</xsl:param>

	<xsl:param name="strBackground_black">Background black</xsl:param>
	<xsl:param name="strBackground_red">Background red</xsl:param>
	<xsl:param name="strBackground_green">Background green</xsl:param>
	<xsl:param name="strBackground_yellow">Background yellow</xsl:param>
	<xsl:param name="strBackground_blue">Background blue</xsl:param>
	<xsl:param name="strBackground_magenta">Background magenta</xsl:param>
	<xsl:param name="strBackground_cyan">Background cyan</xsl:param>
	<xsl:param name="strBackground_white">Background white</xsl:param>
	<xsl:param name="strUnknown_background_color">Unknown background color</xsl:param>


</xsl:stylesheet>
