DROP TABLE CacheTable;
CREATE TABLE CacheTable (Id NUMBER GENERATED ALWAYS as IDENTITY(START with 1 INCREMENT by 1),RequestString VARCHAR(255),ExpiryDate NUMBER(19) NOT NULL,SheetUrl VARCHAR(255),AbsoluteSheetUrl VARCHAR(255),ContentType VARCHAR(255),Xml CLOB NOT NULL,Project VARCHAR(128),Transaction VARCHAR(128));
